# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_app', '0004_auto_20190204_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
