# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant_app', '0005_restaurant_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
